### PR TITLE
fixed counting of answers relevant to Read the docs in Indico

### PR DESCRIPTION
**Pull request by naoe-tatara**
As "Read the Docs" was spelled with small "d" for "Docs", counts were not properly taken for Indico-surveys. Heatmap figure is also thus updated.

### CODE REVIEW

**Comment by bast** [comment]
But are we now counting both "d" and "D" or now only "D"?

**Comment by naoe-tatara** [comment]
Now only "D", as "Read the docs" returned 0 count from Indico-based survey. 
Indico-survey used "D" as a part of alternatives that survey respondents could choose from. Response csv files include thus the chosen alternatives as it is in text format (unlike Typeform-based suveys), so all the observations in the Indico-based survey results include only those with "D" (does this make sense?). So it seems that the original analysis made by @bast returned only counts from Typeform-based survey responses. For some reason, the Typeform-based survey in 2017 used "d" for Read the docs" for a column header, while the one in 2018 used "D".

**Comment by bast** [comment]
So I understand correctly that we should adapt this to extract both "d" and "D"?

**Comment by naoe-tatara** [comment]
> So I understand correctly that we should adapt this to extract both "d" and "D"?

I'm sorry but I am not sure if I understand your message correctly, but what I wanted to say was that Indico-based survey responses do not include anything with small "d", but only large "D". If we adapt this change, then it extracts only "D" from Indico-based survey, but no change was made for Typeform-based survey part. I think the GitHub does not show the difference but the following is the difference, if it is of help:

image

**Comment by bast** [comment]
I meant: would it not be better if we extract both "Read the Docs" and "Read the docs" instead of only one of the two?

**Comment by naoe-tatara** [comment]
Now I checked all the csv files in the data/indico and found that 2018.csv used "d" (I only saw the 2019-c-2020.csv)!!! I fix and send a commit. Thanks!

**Comment by bast** [comment]
Thank you!

**Pull request merged**
