### PR TITLE
made analysis focusing on submissions by online workshop participants

### PR DESCRIPTION
**Pull request by naoe-tatara**
based on the analysis jupyter notebook, made a new notebook to analyze only submissions by online-workshop participants.

### CODE REVIEW

**Comment by bast** [comment]
Same concern as in https://github.com/coderefinery/pre-workshop-survey/pull/20. But same as there, one thing we can do is merge + create an issue where somebody else can combine the notebooks again or factor out the common code into a Python module.

**Comment by naoe-tatara** [comment]
same here; If it can be waited until the end of 19th Sep, I would like to work on it.

**Comment by naoe-tatara** [comment]
I followed the guideline shown above to solve the conflict, but it did not go well.
Step 1, the first line went fine.
After that, the following happened:
```
git checkout -b focus-on-online origin/focus-on-online
fatal: A branch named 'focus-on-online' already exists.
```
I sent this PR with the same branch, but is it better to close this PR and send a new PR?

**Comment by bast** [comment]
> I followed the guideline shown above to solve the conflict, but it did not go well.
> Step 1, the first line went fine.
> After that, the following happened:
> 
> ```
> git checkout -b focus-on-online origin/focus-on-online
> fatal: A branch named 'focus-on-online' already exists.
> ```
> 
> I sent this PR with the same branch, but is it better to close this PR and send a new PR?

I understand that this problem is solved?

**Comment by naoe-tatara** [comment]
Yes, it is solved. (the commit message shows that it is solved, so I thought it is too much if I comment separately)

**Comment by bast** [comment]
Thanks! Only thing I would avoid is to use the name "filter" because that is a function name in Python which is now shadowed and it could be confusing for somebody who is using that function a lot (I do). But this can also become a follow-up issue.

**Comment by naoe-tatara** [comment]
Ah, thanks for pointing out! OK, then I should change the variable name and send a commit soon.

**Comment by naoe-tatara** [comment]
@bast, hope this is good enough?

**Comment by bast** [comment]
Thanks!

**Pull request merged**
